version: '3'
services:
  media_manager:
    build: .
    ports:
      - "8080:80"
    environment:
      - API_PORT=80
      - FFMPEG_PATH=/ffmpeg
      - MP4BOX_Path=/mp4box
      - TEMP_FOLDER=/var/tmp/
      - CONVERTED_FOLDER=converted/
      - COMPRESSED_FOLDER=compressed/
      - SFTP_HOST=localhost
      - SFTP_PORT=2222
      - SFTP_USERNAME=content
      - SFTP_PASSWORD=password
    networks:
      - content_network
networks:
  content_network:
